### PR TITLE
Updated documentation and all public functions

### PR DESCRIPTION
**Pull request by SpencerDH**
I finished updating the public functions so that they return lists, and fixed the apps to accommodate the new structure. I've run each of the apps and confirmed that they run. Additionally, I changed the documentation form for each of the apps to conform to the new format in DSAIRM. I've run all of this through Travis CI, which shows no errors or warnings, so it should be good to go.

### CODE REVIEW

**Comment by andreashandel** [comment]
i can't merge, there are conflicts with files, probably because we both updated. can you take a look at those 2 files and resolve? and appveyor check failed, not sure what the reason is.

**Comment by SpencerDH** [comment]
Okay, I fixed the file conflicts. Now the error messages are the opposite as before, though - it's passing on AppVeyor but failing on Travis CI. I looked at the error logs for the latter; it appears that the package isn't compiling for Linux, but I don't see any errors specific to any file changes. Not sure exactly how to proceed on debugging for that problem  - I don't use Linux, so I'm not sure how to reproduce whatever error Travis CI is getting. Like I said before, the package passes Travis CI on my computer.

**Comment by SpencerDH** [comment]
I added a command to the travis.yml file that extends the amount of time permitted to try to load the package in Linux just now; we'll see in the morning if that gets this working.

**Comment by andreashandel** [comment]
thanks. sometimes travis-ci produces errors not because of the package but because it itself has something going wrong. i look at the log file and if i see that's the reason i ignore. it usually passes again on the next run. will merge now.

**Pull request merged**
