### PR TITLE
Updated Evolutionary Dynamics, Direct Transmission, Environmental Transmission

### PR DESCRIPTION
**Pull request by SpencerDH**
I updated the app.R files with the specifics you mentioned (i.e., removing gather() and so on), and changed the column names from "xvals" to "Time." I ran the apps each several times and they all seem to be working.

### CODE REVIEW

**Comment by andreashandel** [comment]
it fails on both travis-ci and appveyor, see messages above. did you run the package check within Rstudio, did it pass there?

**Comment by SpencerDH** [comment]
I did run the package in RStudio - is the package check something separate? I thought the Travis CI and AppVeyor tests ran automatically when the package was loaded since they're part of the package structure. I'm using R version 5, but even when I update the R version numbers in Travis and AppVeyor I'm not getting an error in running the package.

**Comment by SpencerDH** [comment]
As a brief update on this, I just synced Travis CI with my fork of the repository; after I eat supper I'm going to return to this later this evening to try to reproduce the error message you're getting so I can figure out what's wrong with the code.

**Comment by andreashandel** [comment]
in Rstudio, under the "Build" tab, there's the check command. That runs all the package checks that a package needs to pass to be ok for CRAN. Sometimes travis fails due to issues with their service. But this has error message "simulate_introduction missing", so probably something with package. I'm merging now and then try a local check to see what's going on.

**Comment by andreashandel** [comment]
I fixed the first error, which had to do with some reshuffling in the vignette. The errors now are because you haven't updated the examples yet. I did one. I let you do the others. Also, the documentation for the different functions is not as detailed as in dsairm. Can you check those and add information. Most importantly all information about inputs a function expects and what it returns should be described in detail. Also, feel free to add more examples, they are helpful to users and serve as package checks.

**Pull request merged**
